workflows:
  ios-workflow:
    name: Build Zeus iOS App
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        APP_NAME: "ChatZeus"
    scripts:
      - name: Create and Build Project
        script: | 
          # الخطوة 1: تثبيت الأداة
          brew install xcode-project-gen

          # الخطوة 2: إنشاء مشروع Xcode
          xcode-project-gen --name "$APP_NAME" --type app --interface swiftui --assets "ChatZeus-iOS/icon.png"

          # الخطوة 3: بناء التطبيق (بدون أرشفة أو تصدير)
          xcodebuild build -project "$APP_NAME.xcodeproj" \
                           -scheme "$APP_NAME" \
                           -sdk iphoneos \
                           -configuration Release \
                           CODE_SIGN_IDENTITY="" \
                           CODE_SIGNING_REQUIRED=NO
    artifacts:
      # الخطوة 4: أرشفة مجلد .app الناتج
      - $CM_BUILD_DIR/build/Release-iphoneos/*.app
