workflows:
  ios-unsigned-app:
    name: Build Unsigned iOS App
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Generate Xcode project from Swift files
        script: |
          xcode-project-gen --name ChatZeus --type app --interface swiftui
      - name: Build unsigned IPA
        script: |
          xcodebuild -project "ChatZeus.xcodeproj" \
                    -scheme "ChatZeus" \
                    -sdk iphoneos \
                    -configuration Release \
                    -archivePath $CM_BUILD_DIR/build/ChatZeus.xcarchive \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
                    -archivePath $CM_BUILD_DIR/build/ChatZeus.xcarchive \
                    -exportPath $CM_BUILD_DIR/build/export \
                    -exportOptionsPlist /Users/builder/exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/build/export/*.ipa
